language: python

python:
  - "3.6"

dist: xenial

sudo: false

services:
  - docker

before_install:
  - git clone https://github.com/oceanprotocol/barge
  - cd barge
  - git checkout feature/ocean-contracts
  - export AQUARIUS_VERSION=decentralized
  - bash -x start_ocean.sh --no-dashboard --no-provider 2>&1 > start_ocean.log &
  - cd ..
  - |
      for i in $(seq 1 50); do
        sleep 5
        [ -f "${HOME}/.ocean/ocean-contracts/artifacts/ready" ] && break
      done
      ls -la "${HOME}/.ocean/ocean-contracts/artifacts/"


install: pip install -U tox-travis
script: tox

notifications:
  email: false
