language: python

python:
  - "3.8.6"

dist: focal

sudo: false

services:
  - docker

before_install:
  - python3.8 -m pip install -U pip==20.2.2
  - git clone https://github.com/oceanprotocol/barge
  - cd barge
  - git checkout v3
  - export AQUARIUS_VERSION=v3
  - export CONTRACTS_VERSION=latest
  - bash -x start_ocean.sh --no-dashboard --no-provider 2>&1 > start_ocean.log &
  - cd ..
  - |
      for i in $(seq 1 50); do
        sleep 5
        [ -f "${HOME}/.ocean/ocean-contracts/artifacts/ready" ] && break
      done
      ls -la "${HOME}/.ocean/ocean-contracts/artifacts/"


install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: ${PYPI_USER}
  password: ${PYPI_PASSWORD}
  on:
    tags: true
    repo: oceanprotocol/provider-py
    python: 3.8.6

notifications:
  email: false
