name: Provider tests

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - name: Install dependencies
        run: |
          git clone https://github.com/oceanprotocol/barge
          cd barge
          git checkout v3
          export AQUARIUS_VERSION=v3
          export CONTRACTS_VERSION=latest
          bash -x start_ocean.sh --no-dashboard --no-provider 2>&1 > start_ocean.log &
          cd ..
          for i in $(seq 1 50); do
            sleep 5
            [ -f "$HOME/.ocean/ocean-contracts/artifacts/ready" ] && break
            done
          ls -la "$HOME/.ocean/ocean-contracts/artifacts/"
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions
      - name: Test with tox
        run: tox
